### ISSUE TITLE
Using Merra2BC with nested domains

### ISSUE THREAD

**Issue by jesterstevenwx** [saneku/Merra2BC#2]
In my attempt to use Merra2BC with a nested domain, both zero_fields.py and main.py are looking for wrfbdy_d02 where it doesn't generally exist after running real.exe. Using wrfbdy_d01 for the times gives a broadcast error.

**Comment by saneku** [comment]
you need to modify file names in config.py

**Comment by jesterstevenwx** [comment]
I did that and it didn't work because in wrf_module.py on line 43 it looks only for the d01 met_em files. I edited that to take in config.wrf_met_files and that fixed the problem.

**Comment by saneku** [comment]
please take a look at line 6 in config.py. it sets mask for the met files

**Comment by jesterstevenwx** [comment]
It does, if that gets called properly. When main.py goes to open the met_em files on line 71, it gathers the directory string from config.wrf_met_dir. It then adds the output of wrf_module.get_met_file_by_time(curtime). That function is lines 42 and 43 of wrf_module.py and has on line 43 'return "met_em.d01."+time+".nc"' which isn't calling the mask set in config.wrf_met_files. When trying to do a nested domain which is d02 or greater, getting a met file for d01 is going to produce the error I mentioned when I opened this issue.

**Comment by saneku** [comment]
Sorry for the delay! I get it now. By the way, this bug was actually fixed in another branch a few months back. I just moved the changes to the master branch.
