### ISSUE TITLE
‘o3’ NOT EXIST in MERRA2_300.inst3_3d_aer_Nv/MERRA2_400.inst3_3d_aer_Nv

### ISSUE THREAD

**Issue by yfNJU** [saneku/Merra2BC#3]
I noticed that in the spc_map code for CBMZ-MOSAIC_8bins, there is a section on o3, but in the MERRA2 model layer file used by the mera_files, it doesn't contain the o3.

**Comment by yfNJU** [comment]
Apologize for my unfamiliarity with the MERRA2 dataset, after reviewing the MERRA2 File Specification, CO and o3 are in the inst3_3d_chm_Nv dataset and just need to be merged with inst3_3d_aer_Nv

**Comment by saneku** [comment]
Or you can change the mask for merra2 files and run the utility again
