### ISSUE TITLE
Reference for MOSAIC_8bins aerosols multiplier

### ISSUE THREAD

**Issue by yfNJU** [saneku/Merra2BC#4]
Hi Mr.Alexander Ukhov
I'm curious about the setting of multiplier in spc_map for MOSAIC. I would like to know if there is a reference for such a setting. Thanks!

**Comment by saneku** [comment]
Please read my gmd paper. You will find the information on how to calculate these factors. Cheers

**Comment by yfNJU** [comment]
Thanks a lot! Your paper really really helped me a lot!

**Comment by saneku** [comment]
Thanks for the positive feedback!
